local db = require("lib.db")
db.ensure_schema()

require("server.tests.monitors")
require("server.tests.channels")
require("server.tests.cluster")
require("server.tests.stats")
require("server.tests.status_pages")
require("server.tests.settings")
require("server.tests.nodes")
require("server.tests.reports")
require("server.tests.throttle")
